### ISSUE TITLE
need to change ng-model when control is disabled

### ISSUE THREAD

**Issue by bhushanvaidya3** [frapontillo/angular-bootstrap-switch#84] opened 2015-08-17 18:35 UTC
I have a scenario where I want to programatically change ng-model value on the fly even if the control is disabled. Right now as per my usage, the control only allows changes to ng-model if the control itself is active. Please do let me know if I can achieve this in any way.

Thanks!

**Comment by frapontillo** [comment] 2015-08-17 20:20
Dupe of #67.

**Closed by frapontillo** 2015-08-17 20:20 UTC

**Comment by bhushanvaidya3** [comment] 2015-08-17 20:24
my bad @frapontillo . Will check the original control's posts for the same. Thanks for the update!

**Comment by frapontillo** [comment] 2015-08-17 20:25
No worries, if you open an issue there please make sure you tag me so I can :+1: it as well, it'd be a useful feature.
