### ISSUE TITLE
Binding issues

### ISSUE THREAD

**Issue by Drammy** [frapontillo/angular-bootstrap-switch#68] opened 2015-03-30 12:56 UTC
Hi,

I've found that if I bind switch-active to a model and the model value is false then changing the model in the controller doesn't update the switch UI - its as if it stays in a disabled state even as far as to prevent binding from working and updating the switch state.

Because of this issue I tried binding to switch-readonly and have found that I cannot get it to bind to the same model value at all.

Even switch-readonly="true" and switch-readonly="{{true}}" don't work...?  Is this a bug?

**Comment by frapontillo** [comment] 2015-03-30 16:21
Please provide a live demo on Plunkr. Thanks.

**Comment by Drammy** [comment] 2015-03-30 16:22
OK, will try - nvere really done that before.

DO you have a plunkr handy that I can use as a base?

**Comment by frapontillo** [comment] 2015-03-30 16:30
You can start from here: http://plnkr.co/edit/SWy8YmrVi8IsTa4FuqSZ?p=preview

**Comment by Drammy** [comment] 2015-03-30 16:31
Thanks

**Comment by Drammy** [comment] 2015-03-30 16:42
The plunkr you provided demonstrates the issue already but to demonstrate it further I've added a checkbox bound to the same models...

http://plnkr.co/edit/MP9IvzmNvckFbLh9a8PY?p=preview

You can see that when active both the switch and the checkbox toggle back and forth correctly but when activation is toggled off you'll see the checkbox state update despite it being disabled but the switch state doesn't change and becomes out of sync with the model.  Ideally I would have thought that it should still change state but simply remain disabled so the user cannot change state.

**Comment by frapontillo** [comment] 2015-03-30 17:26
This is a duplicate of #67

**Closed by frapontillo** 2015-03-30 17:26 UTC
Labels: demo-pending

**Comment by Drammy** [comment] 2015-03-30 17:38
Oh, ok. Apologies for wasting your time then. I guess I'll need to look for another angular switch :-(

**Comment by Drammy** [comment] 2015-04-02 21:30
Just thinking this through a bit more...

I would expect this control to sync with the model correctly despite whether or not the jquery control does.  If this AngularJS control loses sync with the model then surely it goes against the AngularJS MVC pattern??

Is there an easy way to make the control sync correctly?

**Comment by frapontillo** [comment] 2015-04-03 07:06
I totally understand what you're saying and share your view on the subject. Unfortunately, changing the behaviour of the original plugin would mean go out of sync whit everything the library provides, and that's something I really don't want to do.

You can still open a bug on the original bug tracker and ask for the feature, I will :+1: it :)

**Comment by Drammy** [comment] 2015-04-03 09:44
Ah, OK I get you.  I'll raise a bug.

I was wondering in the meantime if there's a way to resync on enabling the control?   i.e. if I change the state from disabled tp enabled can the angular control resync at that point?

**Comment by frapontillo** [comment] 2015-04-03 09:45
I can try that, but there would be no point in doing so if your request is accepted ;)

Please link here the bug you're about to open so we can be updated.
Thanks!

**Comment by Drammy** [comment] 2015-04-03 09:52
Fair enough - here's the link..

https://github.com/nostalgiaz/bootstrap-switch/issues/442
