### ISSUE TITLE
bs-select won't read ng-model

### ISSUE THREAD

**Issue by dlwhiteman** [frapontillo/angular-bootstrap-switch#56] opened 2015-01-16 15:59 UTC
I assume I'm doing something wrong, but I cannot get the bs-select element to actually sync with the ng-model.  I did get past the previous issue, which was that I didn't have the correct .js files included.  I have "frapontillo.bootstrap-switch" in my app module list.  I have the following css and js files included in my HTML:

bootstrap-switch.min.css
bootstrap-switch.min.js
angular-bootstrap-switch.min.js

Here is the code I am using:

<bs-switch ng-model="service.output.rtmp.enabled" type="checkbox"></bs-switch>

The value is Off when I visit the page. When I click it to turn it on, and then leave and return to the page, it is back Off.  I added {{ service.output.rtmp.enabled }} next to it to confirm that the switch is indeed not changing the value of the model.

What else am I possibly missing?  I am temporarily using a similar plugin called angular-toggle-switch that I am able to get working, but I would prefer to use your plugin, as it has a richer set of features.  I tried to look at the example on this site for guidance, but it's hard to compare to that one, as it uses a different set of file names in the required libraries.

**Comment by Splaktar** [comment] 2015-01-18 00:41
Are you running into #52?

**Comment by dlwhiteman** [comment] 2015-01-18 02:06
That must be it, because the bootstrap-switch widget is on a panel that is made visible using ng-switch-when and ng-include to demand load templates for a tree-based settings dialog.  So I guess I will need to try that workaround suggested in #52.  I think I can accomplish this, because ng-include provides an onload attribute to run some code after the page is loaded.  I won't be able to test this theory until Monday.  Thanks for the tip!

**Comment by frapontillo** [comment] 2015-01-19 08:07
Duplicate of #52.

**Closed by frapontillo** 2015-01-19 08:07 UTC
